#!/usr/bin/env python3

# Created by: Adam Diwani
# Created on: December 6, 2020
# This module contains constants that I can use


import random

random_number = random.randint(1,10)



def main():
    #this function Guesses a magic number
    
    #input
    user_input = int(input("Insert a number from 1-10: "))
    print("")
    
    #process

    if user_input == 5:
        #Output
         print("")
         print("correct!")
   
    else:
        print("Wrong number. Correct answer is 5.")

if __name__ == "__main__":
    main()
